export { Footer } from './Footer'
export { InfoBlock } from './Info'
export { Main } from './Main'
export { NavBar, NavLink } from './Nav'
export { Heading } from './Heading'
export { Paragraph } from './Paragraph'
