export { Footer } from './Footer'
export { Main } from './Main'
export { NavBar, NavLink } from './Nav'
export { InfoLink, InfoBlock } from './Info'
export { AwardLink } from './Award'
export { BookLink } from './Book'
export { BookCategoryLink } from './BookCategory'
export { InfoCategoryLink } from './InfoCategory'
export { CompetitionLink } from './Competition'
